# Generated by Django 5.2.8 on 2025-11-23 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONSTANCIA_RESIDENCIA', 'Constancia de residencias')], max_length=50)),
                ('nombre_alumno', models.CharField(max_length=150)),
                ('numero_control', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado')], default='generado', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
