# Generated by Django 5.2.8 on 2025-11-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('CONST_RES', 'Constancia de Residencias'), ('CONST_SERV', 'Constancia de Servicio Social'), ('CONST_PRA', 'Constancia de Prácticas Profesionales')], max_length=50),
        ),
    ]
