# Generated by Django 5.2.8 on 2025-12-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_reporte_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='carrera',
            field=models.CharField(choices=[('ING_BIOQUIMICA', 'Ingeniería Bioquímica'), ('ING_SEMICONDUCTORES', 'Ingeniería en Semiconductores'), ('CONTADOR_PUBLICO', 'Contador Público'), ('ING_ADMINISTRACION', 'Ingeniería en Administración'), ('ING_DESARROLLO_APLICACIONES', 'Ingeniería en Desarrollo de Aplicaciones'), ('ING_ELECTRICA', 'Ingeniería Eléctrica'), ('ING_ELECTRONICA', 'Ingeniería Electrónica'), ('ING_ENERGIAS_RENOVABLES', 'Ingeniería en Energías Renovables'), ('ING_GESTION_EMPRESARIAL', 'Ingeniería en Gestión Empresarial'), ('ING_INDUSTRIAL', 'Ingeniería Industrial'), ('ING_LOGISTICA', 'Ingeniería en Logística'), ('ING_MATERIALES', 'Ingeniería en Materiales'), ('ING_MECATRONICA', 'Ingeniería Mecatrónica'), ('ING_MECANICA', 'Ingeniería Mecánica'), ('ING_QUIMICA', 'Ingeniería Química'), ('ING_SISTEMAS_COMPUTACIONALES', 'Ingeniería en Sistemas Computacionales')], default='ING_SISTEMAS_COMPUTACIONALES', max_length=60),
            preserve_default=False,
        ),
    ]
